artifacts_dir: artifacts


data_ingestion:
    ingestion_dir: artifacts/data_ingestion
    books_data_file: artifacts/data_ingestion/books.csv
    ratings_data_file: artifacts/data_ingestion/ratings.csv
    users_data_file: artifacts/data_ingestion/users.csv
    
data_validation:
    validation_dir: artifacts/data_validation
    status_filepath: artifacts/data_validation/status.txt
    required_files: ["books.csv", "ratings.csv", "users.csv"]

data_transformation:
    transformation_dir: artifacts/data_transformation
    books_df_dir: artifacts/data_transformation/books.csv
    final_df_dir: artifacts/data_transformation/final.csv
